name: Type checks

on: [ push, pull_request ]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Tags are needed to install DL-Registry
      - uses: actions/setup-python@v6
        with:
          python-version: '3.9'
      - name: Install dependencies and project
        run: |
          pip install --upgrade pip
          pip install -r requirements.dev.txt
          pip install .[dev]
      - name: Run mypy
        run: mypy datalad_registry datalad_registry_client
